# Generated by Django 4.1 on 2022-11-23 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_address_order_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customre',
            new_name='customer',
        ),
    ]
